In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

CREATING LIST

In [4]:
list = [4,85,1,-85]

In [5]:
type(list)

list

In [6]:
arr= np.array(list)  #converting list to array

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(list)

list

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [11]:
np.arange(10,25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
np.arange(-6,9)

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [13]:
np.arange(-8)

array([], dtype=int32)

In [14]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [17]:
np.zeros(6,dtype=str)

array(['', '', '', '', '', ''], dtype='<U1')

In [18]:
np.zeros(6,dtype=bool)

array([False, False, False, False, False, False])

In [19]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones(6, dtype=int)

array([1, 1, 1, 1, 1, 1])

In [21]:
np.random.rand(3,4)

array([[0.86815258, 0.68418733, 0.31073632, 0.18092242],
       [0.14668108, 0.36820115, 0.57157307, 0.93986625],
       [0.88855782, 0.42742198, 0.53371236, 0.27432596]])

In [22]:
np.random.randint(1.5,4.55)

2

In [23]:
np.random.randint(100,1000)

899

In [24]:
np.random.randint(100,845,4)

array([605, 601, 669, 460])

In [25]:
np.random.random(3)

array([0.66087925, 0.8369852 , 0.11571859])

In [26]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## SLICING IN MATRIX

In [33]:
b=np.random.randint(10,30,(4,5))
b

array([[13, 29, 16, 24, 20],
       [24, 24, 25, 26, 25],
       [20, 22, 27, 29, 15],
       [27, 24, 25, 19, 27]])

In [35]:
type(b)

numpy.ndarray

In [34]:
b[1:3]

array([[24, 24, 25, 26, 25],
       [20, 22, 27, 29, 15]])

In [38]:
b[3,4]

27

In [39]:
b[2,-2]

29

# numpy operations

In [41]:
b[::2]

array([[13, 29, 16, 24, 20],
       [20, 22, 27, 29, 15]])

In [42]:
b[::-2]

array([[27, 24, 25, 19, 27],
       [24, 24, 25, 26, 25]])

In [43]:
b

array([[13, 29, 16, 24, 20],
       [24, 24, 25, 26, 25],
       [20, 22, 27, 29, 15],
       [27, 24, 25, 19, 27]])

In [44]:
b.max()

29

In [45]:
b[::-1]

array([[27, 24, 25, 19, 27],
       [20, 22, 27, 29, 15],
       [24, 24, 25, 26, 25],
       [13, 29, 16, 24, 20]])

In [46]:
krr=[56,11,78,55]

In [47]:
krr[::-1]

[55, 78, 11, 56]

In [49]:
hit=np.random.randint(10,100,(10,10))
hit

array([[51, 33, 79, 58, 66, 19, 34, 23, 51, 78],
       [63, 58, 89, 15, 34, 56, 14, 15, 20, 13],
       [68, 30, 64, 68, 49, 52, 74, 34, 92, 92],
       [90, 72, 87, 35, 24, 56, 31, 44, 52, 27],
       [32, 59, 48, 59, 36, 64, 54, 62, 65, 26],
       [90, 39, 95, 72, 71, 19, 79, 14, 33, 19],
       [20, 54, 34, 38, 76, 45, 98, 87, 14, 77],
       [19, 84, 50, 64, 25, 37, 47, 29, 31, 16],
       [14, 49, 22, 35, 43, 27, 53, 28, 13, 81],
       [85, 87, 60, 54, 22, 28, 85, 94, 31, 15]])

In [50]:
hit[:,3]  #COLUMN PRINTING

array([58, 15, 68, 35, 59, 72, 38, 64, 35, 54])

In [52]:
hit[1:4,3:6]

array([[15, 34, 56],
       [68, 49, 52],
       [35, 24, 56]])

# MASKING

In [53]:
id(hit)

1797665504304

In [54]:
hit>50

array([[ True, False,  True,  True,  True, False, False, False,  True,
         True],
       [ True,  True,  True, False, False,  True, False, False, False,
        False],
       [ True, False,  True,  True, False,  True,  True, False,  True,
         True],
       [ True,  True,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False,  True, False,  True,  True,  True,  True,
        False],
       [ True, False,  True,  True,  True, False,  True, False, False,
        False],
       [False,  True, False, False,  True, False,  True,  True, False,
         True],
       [False,  True, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
         True],
       [ True,  True,  True,  True, False, False,  True,  True, False,
        False]])

In [55]:
hit[hit>50]

array([51, 79, 58, 66, 51, 78, 63, 58, 89, 56, 68, 64, 68, 52, 74, 92, 92,
       90, 72, 87, 56, 52, 59, 59, 64, 54, 62, 65, 90, 95, 72, 71, 79, 54,
       76, 98, 87, 77, 84, 64, 53, 81, 85, 87, 60, 54, 85, 94])